version: '2'
services:
  mongo:
    image: mongo
    expose:
      - "27017"

  redis:
    image: redis
    volumes:
      - ./data:/data
    expose:
      - "6379"

  bot:
    image: registry.gitlab.com/gumino-node-apps/astone-bot
    links:
        - mongo
        - redis
    ports:
        - "9005:9001"


